### ISSUE TITLE
Deploy navbar/health-dashboard/mgmt-console as a base bootstrap-deploy

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-management-console#30]

**Comment by buggtb** [comment]
Don't break it Rob!

*Tom Barber*
*Director | Spicule LTD*
*Phone* : 07456865296
*Website* : https://spicule.co.uk

*Databricks Certified*

**Comment by rtapella** [comment]
no promises @buggtb 😆 
wrong repo for this ticket
